"""Shared helpers for the SimpleQ CLI."""

from __future__ import annotations

import importlib
import json
import sys
from dataclasses import replace
from json import JSONDecodeError
from pathlib import Path
from typing import Any

import typer

from simpleq.client import SimpleQ
from simpleq.task import TaskDefinition, TaskHandle


def make_client(
    *,
    endpoint_url: str | None = None,
    region: str | None = None,
) -> SimpleQ:
    """Build a SimpleQ client for CLI commands."""
    return SimpleQ(endpoint_url=endpoint_url, region=region)


def import_modules(module_names: list[str], *, reload: bool = False) -> None:
    """Import modules that register tasks."""
    for module_name in module_names:
        module = importlib.import_module(module_name)
        if reload:
            importlib.reload(module)


def load_registered_tasks(
    simpleq: SimpleQ, module_names: list[str], *, reload: bool = False
) -> None:
    """Import modules and copy discovered task definitions into ``simpleq``."""
    import_modules(module_names, reload=reload)
    for module_name in module_names:
        module = sys.modules.get(module_name)
        if module is None:
            continue
        for value in vars(module).values():
            if isinstance(value, TaskHandle):
                simpleq.registry.register(
                    rebind_task_definition(simpleq, value.definition)
                )
            elif isinstance(value, SimpleQ):
                for task_name in value.registry.names():
                    simpleq.registry.register(
                        rebind_task_definition(simpleq, value.registry.get(task_name))
                    )


def rebind_task_definition(
    simpleq: SimpleQ, definition: TaskDefinition
) -> TaskDefinition:
    """Rebind an imported task definition onto the target SimpleQ client."""
    queue_ref = definition.queue_ref
    if queue_ref is None:
        return replace(definition, queue_ref=None)
    return replace(definition, queue_ref=simpleq.resolve_queue(queue_ref))


def module_paths(module_names: list[str]) -> list[Path]:
    """Return file paths for imported modules."""
    paths: list[Path] = []
    for module_name in module_names:
        module = sys.modules.get(module_name)
        module_file = getattr(module, "__file__", None)
        if module_file is not None:
            paths.append(Path(module_file))
    return paths


def snapshot_module_mtimes(paths: list[Path]) -> dict[Path, float]:
    """Snapshot module modification times for auto-reload."""
    return {path: path.stat().st_mtime for path in paths if path.exists()}


def modules_changed(previous: dict[Path, float]) -> bool:
    """Return whether any watched module file changed."""
    for path, old_mtime in previous.items():
        if not path.exists():
            return True
        if path.stat().st_mtime != old_mtime:
            return True
    return False


def parse_invocation_payload(
    *,
    args_json: str | None = None,
    kwargs_json: str | None = None,
    payload_json: str | None = None,
) -> tuple[tuple[Any, ...], dict[str, Any]]:
    """Parse CLI JSON into task args and kwargs."""

    def parse_json(value: str, *, option_name: str) -> Any:
        try:
            return json.loads(value)
        except JSONDecodeError as exc:
            raise typer.BadParameter(f"{option_name} must contain valid JSON.") from exc

    provided = [value is not None for value in (args_json, kwargs_json, payload_json)]
    if sum(provided) > 1:
        raise typer.BadParameter(
            "Use only one of --args-json, --kwargs-json, or --payload-json."
        )
    if args_json is not None:
        parsed = parse_json(args_json, option_name="--args-json")
        if not isinstance(parsed, list):
            raise typer.BadParameter("--args-json must decode to a JSON array.")
        return tuple(parsed), {}
    if kwargs_json is not None:
        parsed = parse_json(kwargs_json, option_name="--kwargs-json")
        if not isinstance(parsed, dict):
            raise typer.BadParameter("--kwargs-json must decode to a JSON object.")
        return (), parsed
    if payload_json is not None:
        parsed = parse_json(payload_json, option_name="--payload-json")
        if isinstance(parsed, list):
            return tuple(parsed), {}
        if isinstance(parsed, dict):
            return (), parsed
        return (parsed,), {}
    return (), {}


def scaffold_files() -> dict[str, str]:
    """Return files generated by ``simpleq init``."""
    return {
        "simpleq_app.py": '''"""Starter SimpleQ application."""

from __future__ import annotations

from pydantic import BaseModel

from simpleq import SimpleQ

sq = SimpleQ()
queue = sq.queue("emails", dlq=True, wait_seconds=0)


class EmailPayload(BaseModel):
    to: str
    subject: str
    body: str


@sq.task(queue=queue, schema=EmailPayload)
def send_email(payload: EmailPayload) -> None:
    print(f"Sending {payload.subject} to {payload.to}")


def main() -> None:
    send_email.delay_sync(
        to="user@example.com",
        subject="Hello",
        body="SimpleQ is ready.",
    )
    sq.worker(queues=[queue], concurrency=1).work_sync(burst=True)


if __name__ == "__main__":
    main()
''',
        ".env.example": """AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
SIMPLEQ_ENDPOINT_URL=http://localhost:4566
""",
    }
